# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af813fda15014b57265f505c968dbbd064016a568174e3d0918d130ba3b02bbf7b6c49bbeca7b987b138759fac3075bdca6de8d43dc23a808a39d3179caad354

test:
  secret_key_base: ac5ffdc3f5c590eb320aec037ad8d072926cc0192bd9348421ca87c2860af6f09b436a8899bd6082c48455dd3a2162cc382ec656cca723bd324daa64b2716d76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
